---
title: "P8105 HW1"
author: "Qingzhen Sun"
output: github_document
---

```{r}
library(tidyverse)
library(ggplot2)
```

```{r}
data("penguins", package = "palmerpenguins")
```
#Problem 1
```{r}
view(penguins)
nrow(penguins)
ncol(penguins)
summary(penguins)
# There are 8 variable in the table: species, island, bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g, sex and year.
# The penguins data sheet has 344 row and 8 column.
# The mean of flipper length is 200.9 mm.


# The scatterplot:
ggplot(penguins, aes(x= bill_length_mm, y=flipper_length_mm)) + geom_point(aes(color=species))
ggsave
```
#Problem 2
```{r}
# Create the data frame.
df = tibble(
  RS = rnorm(10),
  logical = RS > 0,
  C = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10"),
  L = factor(c("A", "B", "C", "A", "A", "B", "C", "A", "B", "C"))
)
df
```

```{r, results='hide'}
# The RS variable has the mean of around 0.307.
mean(as.numeric(df$RS))
# The logical variable has the mean of 0.6.
mean(as.numeric(df$logical))
# The C variable has the mean of 5.5.
mean(as.numeric(df$C))
# The L variable has the mean of 1.9.
mean(as.numeric(df$L))

```